# config/meta.yml

meta_product_name: "Nearbuy"
meta_title: "Nearbuy - Your local marketplace"
meta_description: "It's a really cool product!"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
